*** Variables ***
@{CURRENCY_DROPDOWN_DATA}=    US Dollar    Euro
${DEFAULT_CURRENCY_SYMBOL}=    US Dollar
&{CURRENCY_RATE_DATA}=    US Dollar=1.00    Euro=0.86    #create dictionary contains currency rates

@{MENU_CATEGORIES_DATA}=    Computers    Electronics    Apparel    Digital downloads    Books    Jewelry    Gift Cards
@{MENU_SUB_CATEGORIES_DATA}=    Desktops    Notebooks    Software    Camera & photo    Cell phones    Others    Shoes    Clothing    Accessories

${DEFAULT_WISHLIST_NUMBER}=    0
${DEFAULT_SHOPPING_CART_NUMBER}=    0