*** Variables ***
${WELCOME_TEXT_DATA}    []Online shopping is the process consumers go through to purchase products or services over the Internet. You can edit this in the admin site.If you have questions, see the Documentation, or post in the Forums at nopCommerce.com
${PLACEHOLDER_SEARCHBOX_TEXT_DATA}    Search store
${EXCELLENT_RADIO_TEXT_DATA}    Excellent
${GOOD_RADIO_TEXT_DATA}    Good
${POOR_RADIO_TEXT_DATA}    Poor 
${VERY_BAD_RADIO_TEXT_DATA}    Very bad
@{CURRENCY_DROPDOWN_DATA}=    US Dollar    Euro
